# Generated by Django 5.0.3 on 2026-01-29 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bridgetoken',
            new_name='doorman_bri_custome_c6586e_idx',
            old_name='doorman_bri_custome_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='bridgetoken',
            new_name='doorman_bri_expires_d1de02_idx',
            old_name='doorman_bri_expires_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='magiccode',
            new_name='doorman_mag_target__fb31c0_idx',
            old_name='doorman_mag_target__g7h8i9_idx',
        ),
        migrations.RenameIndex(
            model_name='magiccode',
            new_name='doorman_mag_expires_74f4dd_idx',
            old_name='doorman_mag_expires_j0k1l2_idx',
        ),
    ]
