# Generated by Django 5.2.11 on 2026-02-21 16:09

import django.db.models.deletion
import doorman.models.bridge_token
import doorman.models.magic_code
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorman', '0002_rename_doorman_bri_custome_a1b2c3_idx_doorman_bri_custome_c6586e_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bridgetoken',
            options={'ordering': ['-created_at'], 'verbose_name': 'link de acesso', 'verbose_name_plural': 'links de acesso'},
        ),
        migrations.AlterModelOptions(
            name='identitylink',
            options={'verbose_name': 'perfil de usuário', 'verbose_name_plural': 'perfis de usuário'},
        ),
        migrations.AlterModelOptions(
            name='magiccode',
            options={'ordering': ['-created_at'], 'verbose_name': 'código de verificação', 'verbose_name_plural': 'códigos de verificação'},
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='audience',
            field=models.CharField(choices=[('web_checkout', 'Checkout'), ('web_account', 'Conta'), ('web_support', 'Suporte'), ('web_general', 'Geral')], default='web_general', help_text='Escopo do token', max_length=20, verbose_name='audiência'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='customer_id',
            field=models.UUIDField(db_index=True, help_text='UUID do cliente no Guestman', verbose_name='ID do cliente'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='expires_at',
            field=models.DateTimeField(default=doorman.models.bridge_token.default_expiry, verbose_name='expira em'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='metadados'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='source',
            field=models.CharField(choices=[('manychat', 'ManyChat'), ('internal', 'Interno'), ('api', 'API')], default='manychat', max_length=20, verbose_name='origem'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='token',
            field=models.CharField(db_index=True, default=doorman.models.bridge_token.generate_token, max_length=64, unique=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='usado em'),
        ),
        migrations.AlterField(
            model_name='bridgetoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doorman_bridge_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='identitylink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='identitylink',
            name='customer_id',
            field=models.UUIDField(db_index=True, help_text='UUID do cliente no Guestman', unique=True, verbose_name='ID do cliente'),
        ),
        migrations.AlterField(
            model_name='identitylink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doorman_identity_link', to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='tentativas'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='code',
            field=models.CharField(default=doorman.models.magic_code.generate_code, max_length=6, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='customer_id',
            field=models.UUIDField(blank=True, help_text='UUID do cliente no Guestman', null=True, verbose_name='ID do cliente'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='delivery_method',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='método de envio'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='expires_at',
            field=models.DateTimeField(default=doorman.models.magic_code.default_code_expiry, verbose_name='expira em'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='máximo de tentativas'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('verify_contact', 'Verificar Contato')], default='login', max_length=20, verbose_name='finalidade'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='enviado em'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('verified', 'Verificado'), ('expired', 'Expirado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='target_value',
            field=models.CharField(db_index=True, help_text='Telefone em E.164 ou email.', max_length=255, verbose_name='valor destino'),
        ),
        migrations.AlterField(
            model_name='magiccode',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='verificado em'),
        ),
    ]
